stages:
  - deploy_dev

deploy_dev:
  image: alpine/ansible:latest
  stage: deploy_dev

  before_script:
    - apk add --no-cache openssh-client sshpass
    - test -n "$DEPLOY_PASSWD" || { echo "DEPLOY_PASSWD is not set"; exit 1; }
    - sshpass -p "$DEPLOY_PASSWD" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no "$DEPLOY_USER@$DEPLOY_DEV_HOST" "echo SSH_LOGIN_OK"

  script:
    - |
      ANSIBLE_ROLES_PATH=ansible/roles \
      ANSIBLE_HOST_KEY_CHECKING=False \
      ansible-playbook \
        -i ansible/inventory/dev.yaml \
        ansible/playbooks/deploy.yml \
        --extra-vars "docker_image=nginx:mainline-alpine3.24-slim"

  tags:
    - simple-runner