all:
  children:
    app:
      hosts:
        dev:
          ansible_host: "{{ lookup('env', 'DEPLOY_DEV_HOST') }}"
          ansible_user: "{{ lookup('env', 'DEPLOY_USER') }}"
          ansible_password: "{{ lookup('env', 'DEPLOY_PASSWD') }}"
          ansible_ssh_common_args: "-o PreferredAuthentications=password -o PubkeyAuthentication=no"
#        prod:
#          ansible_host: "{{ lookup('env', 'DEPLOY_PROD_HOST') }}"
#          ansible_user: "{{ lookup('env', 'DEPLOY_USER') }}"
#          ansible_password: "{{ lookup('env', 'DEPLOY_PASSWD') }}"
#          ansible_ssh_common_args: "-o PreferredAuthentications=password -o PubkeyAuthentication=no"