all:
  children:
    app:
      hosts:
        dev:
          ansible_host: "{{ lookup('env', 'DEPLOY_DEV_HOST') }}"
          ansible_user: "{{ lookup('env', 'DEPLOY_USER') }}"
          ansible_password: "{{ lookup('env', 'DEPLOY_PASSWD') }}"
        prod:
          ansible_host: "{{ lookup('env', 'DEPLOY_PROD_HOST') }}"
          ansible_user: "{{ lookup('env', 'DEPLOY_USER') }}"
          ansible_password: "{{ lookup('env', 'DEPLOY_PASSWD') }}"
